//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Castor.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceRu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceRu() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Castor.Properties.ResourceRu", typeof(ResourceRu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///
        ///&lt;tr&gt;
        ///    &lt;th&gt;{0}&lt;/th &gt;
        ///    &lt;td&gt;{1}&lt;/td&gt; 
        ///    &lt;td&gt;{2}&lt;/td&gt; 
        ///&lt;/tr&gt; 
        ///.
        /// </summary>
        internal static string BlockTrLine {
            get {
                return ResourceManager.GetString("BlockTrLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///&lt;tr&gt; 
        ///    &lt;th&gt; {0}&lt;/th&gt; 
        ///    &lt;th&gt; {1}&lt;/th&gt; 
        ///    &lt;th&gt; {9}&lt;/th&gt; 
        ///&lt;/tr &gt;
        ///&lt;tr&gt;
        ///&lt;td&gt; Психозы&lt;/td &gt;
        ///    &lt;td&gt;{2}&lt;/td&gt; 
        ///    &lt;td&gt;{10}&lt;/td&gt; 
        ///&lt;/tr&gt; 
        ///&lt;tr&gt; 
        /// &lt;td&gt;Шизофрения&lt;/td&gt;  
        ///    &lt;td&gt;{3}&lt;/td&gt;
        ///    &lt;td&gt;{11}&lt;/td&gt;
        ///&lt;/tr&gt; 
        ///&lt;tr&gt; 
        /// &lt;td&gt;Умственная отсталость&lt;/td&gt;   
        ///    &lt;td&gt;{4}&lt;/td&gt;
        ///    &lt;td&gt;{12}&lt;/td&gt;
        ///&lt;/tr&gt; 
        ///&lt;tr&gt; 
        /// &lt;td&gt;Непсихотические расстройства&lt;/td&gt;
        ///    &lt;td&gt;{5}&lt;/td&gt;
        ///    &lt;td&gt;{13}&lt;/td&gt;
        ///&lt;/tr&gt; 
        ///&lt;tr&gt; 
        /// &lt;td&gt;Наркологические&lt;/td&gt;   
        ///    &lt;td&gt;{6}&lt;/td&gt;
        ///    &lt;td&gt;{14}&lt;/td&gt;
        ///&lt;/tr&gt; 
        ///&lt;tr&gt; 
        /// &lt;td&gt;  - из них с [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BlockTrTd {
            get {
                return ResourceManager.GetString("BlockTrTd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CREATE TABLE &quot;Forced&quot; (
        ///    &quot;Id&quot; INTEGER NOT NULL CONSTRAINT &quot;PK_Forced&quot; PRIMARY KEY AUTOINCREMENT,
        ///    &quot;RootId&quot; INTEGER NOT NULL,
        ///    &quot;Start&quot; TEXT NOT NULL,
        ///    &quot;End&quot; TEXT NULL,
        ///    &quot;Patientid&quot; INTEGER NOT NULL,
        ///    &quot;Visitid&quot; INTEGER NOT NULL,
        ///    &quot;Type&quot; INTEGER NULL,
        ///    &quot;Courtname&quot; TEXT NULL
        ///).
        /// </summary>
        internal static string create_forced {
            get {
                return ResourceManager.GetString("create_forced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt; 
        ///&lt;html&gt; 
        ///&lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html;charset=UTF-8&apos;&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///    p {{
        ///        font-size: 14pt;
        ///    }}
        ///    table {{                        /* This CSS rule makes the table use 100% of its parent container&apos;s width */
        ///        width: 100%;
        ///        border-collapse: collapse;  /* Optional: Makes borders look nicer */
        ///        font-size: 12pt;
        ///    }}
        ///
        ///    th, td {{
        ///        border: 1px solid black;
        ///        padding: 2px;
        ///        text-align: left;
        ///    [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string MonthReport {
            get {
                return ResourceManager.GetString("MonthReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;p style=\&quot;font-size: 16pt;\&quot;&gt;Отчет за период {0} - {1} 6 женского отделения первого эпизода&lt;/p&gt;.
        /// </summary>
        internal static string MonthReportHeaderString {
            get {
                return ResourceManager.GetString("MonthReportHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;p&gt;ОШИБКА В ДИАГНОЗАХ ПОСТУПЛЕНИЯ&lt;/p&gt;.
        /// </summary>
        internal static string MonthReportInError {
            get {
                return ResourceManager.GetString("MonthReportInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;p&gt;ОШИБКА В ДИАГНОЗАХ ВЫПИСКИ&lt;/p&gt;.
        /// </summary>
        internal static string MonthReportOutError {
            get {
                return ResourceManager.GetString("MonthReportOutError", resourceCulture);
            }
        }
    }
}
