//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Castor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sqliteConnection {
            get {
                return ((string)(this["sqliteConnection"]));
            }
            set {
                this["sqliteConnection"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-J9NFCEV;Initial Catalog=deps;Integrated Security=True;Encrypt" +
            "=False")]
        public string sqlserverConnection {
            get {
                return ((string)(this["sqlserverConnection"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int contextValiant {
            get {
                return ((int)(this["contextValiant"]));
            }
            set {
                this["contextValiant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long LastConnectedUserId {
            get {
                return ((long)(this["LastConnectedUserId"]));
            }
            set {
                this["LastConnectedUserId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2704")]
        public long LastSelectedDep {
            get {
                return ((long)(this["LastSelectedDep"]));
            }
            set {
                this["LastSelectedDep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Host=172.23.1.220;Port=5432;Database=med;Username=SOLUTION_MED;Password=elsoft")]
        public string postgreeConnection {
            get {
                return ((string)(this["postgreeConnection"]));
            }
            set {
                this["postgreeConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Castor.gui.movebook.Thebook")]
        public string StartLoadingPage {
            get {
                return ((string)(this["StartLoadingPage"]));
            }
            set {
                this["StartLoadingPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AskUserBeforeStart {
            get {
                return ((bool)(this["AskUserBeforeStart"]));
            }
            set {
                this["AskUserBeforeStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1482")]
        public long RootDepartmentId {
            get {
                return ((long)(this["RootDepartmentId"]));
            }
            set {
                this["RootDepartmentId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Server-mis\\общая папка\\6 отделение")]
        public string dbPrefix {
            get {
                return ((string)(this["dbPrefix"]));
            }
            set {
                this["dbPrefix"] = value;
            }
        }
    }
}
